import type { MapData } from './teamMap.types'

export const mockTeamMapData: MapData = {
  // Dùng ảnh mock landscape 
  backgroundImageUrl: 'https://images.unsplash.com/photo-1524661135-423995f22d0b?auto=format&fit=crop&q=80&w=2000&h=1500',
  width: 2000,
  height: 1500,
  stations: [
    {
      id: 'st-1',
      name: 'Trạm 1: Khởi động',
      code: 'M-01',
      x: 15,
      y: 20,
      status: 'completed',
      points: 100,
      description: 'Hoàn thành thử thách khởi động tại khu vực cổng chính. Người chơi cần tìm ra mật thư được giấu trong khu vực đài phun nước để bắt đầu hành trình chinh phục giải đấu hôm nay.',
    },
    {
      id: 'st-2',
      name: 'Trạm 2: Vượt chướng ngại vật',
      code: 'M-02',
      x: 45,
      y: 35,
      status: 'active',
      points: 200,
      description: 'Vượt qua các chướng ngại vật liên hoàn bao gồm: trèo qua tường lốp xe, vượt cầu khỉ và bò dưới lưới thép gai. Đòi hỏi tinh thần đồng đội cực cao để hỗ trợ nhau hoàn thành nhiệm vụ trong thời gian sớm nhất có thể. Đội nào hoàn thành dưới 5 phút sẽ được cộng thêm điểm thưởng.',
    },
    {
      id: 'st-3',
      name: 'Trạm 3: Giải đố',
      code: 'M-03',
      x: 30,
      y: 70,
      status: 'locked',
      points: 150,
      description: 'Cần hoàn thành Trạm 2 để mở khoá Trạm 3.',
    },
    {
      id: 'st-4',
      name: 'Trạm 4: Bắn cung',
      code: 'M-04',
      x: 80,
      y: 50,
      status: 'locked',
      points: 300,
      description: 'Khu vực bắn cung tính điểm.',
    },
    {
      id: 'st-5',
      name: 'Trạm Đích: Về đích',
      code: 'M-05',
      x: 85,
      y: 85,
      status: 'locked',
      points: 500,
      description: 'Về đích và nhận chứng nhận.',
    },
  ],
}
